server:
  port: 7900
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema:
    - classpath:schema.sql
    data:
    - classpath:data.sql
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}} #此实例注册到eureka服务端的唯一实例Id,其组成为${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/


security:
  user:                 
    name: user         #安全访问用户名
    password: password123      #安全访问密码
  basic:
    enabled: true      #默认为true,用户名：user;密码：启动项目时在控制台会打印出来，例如：Using default security password: c60ad8ae-6401-4aa5-af3e-5b3400d86546,启动安全访问，需要通过用户名密码访问 

#上面设置了安全用户名和密码
management:
  security: 
    enabled: false       #如果management.security.enabled的值是false的话，除开health接口还依赖endpoints.health.sensitive的配置外，其他接口都不需要输入用户名和密码了
    

#logging:
#  level:
#    root：INFO
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.basicEx
#    org.hibernate.type.descriptor.sql.BasicExtractor:TRACE
#    com.yunjipin: DEBUG
