server:
  port: 8761
#spring:
#  application:
#    name: eurekaServer
eureka:
  server:
    #Eureka的自我保护不会剔除应下线了的应用，但STS工具会，因为STS他会调用spring boot shutdown hook（停止的钩子），会想eurakaserver申请剔除下线了的应用
    enable-self-preservation: false 
    #eviction-interval-timer-in-ms: 30   清楚间隔（单位毫秒，默认是60*1000） 
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/

#  dashboard:
#    enabled: true
#    path: /x      #eureka做集群是使用，在生成环境指显示暴露一个eureka的访问路径，避免别人识别，加上一定的访问的后缀，比如/x
security:
  basic:
    enabled: true   #需要输入用户名密码才能访问，同时需要添加springboot的security依赖
  user:
    name: user
    password: password123
#spring:
#  freemarker:
#    prefer-file-system-access: false


#1、监控   总共请求多少次，有多少次失败，假设失败10%断路器打开
#2、断路器的状态
#3、风流
#4、自我修复（断路器状态的修复）
